version: '3.6'
services:
  mysql-service:
    image: mysql:8.0
    container_name: my_sql_container
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=my_rest_db
    ports:
      - 3311:3306
    restart: always

  spring-boot-service:
    build: .
    container_name: spring_boot_container
    ports:
      - 9011:9090
    depends_on:
      - mysql-service
    restart: always

  bruno-service:
    build: 
      context: .
      dockerfile: Dockerfile-Bruno
    container_name: bruno_container
    depends_on:
      - spring-boot-service
    volumes:
      - ./Import:/app/ProductRestAPI_for_Docker/results
    restart: always

